Repository Shravan107/OSSEAssignmentGroup01, pull requests merged in 2021-12, with the labels that each got.

#3 student model added
  spring/src/main/java/com/spring/spring/controller/HomeController.java
  spring/src/main/java/com/spring/spring/model/Student.java
Labels: enhancement

#14 Remove unused global variable issue fix
  spring/src/main/java/com/spring/spring/controller/AdminController.java
Labels: minor issue, issue fix

#21 More fields for Admin Model Issue fix
  spring/src/main/java/com/spring/spring/model/Admin.java
Labels: enhancement

#20 Fix classes route and READme
  README.md
  spring/src/main/java/com/spring/spring/controller/TeacherController.java
Labels: issue fix
